# Generated by Django 5.1.2 on 2024-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='source_station',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pnr',
            name='train_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='destination_station',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
